/**
 * Local TCP bridge between CM (Electron main) and the BeamNG Lua extension
 * `beamcmEditorSync.lua`.
 *
 * Mirrors `VoiceBridgeSocket` in shape — newline-delimited UTF-8 frames over
 * loopback TCP — but carries world-editor op envelopes instead of audio.
 *
 * Wire format (both directions, one frame per line):
 *   H|<luaBuildInfoJson>\n              Lua → CM: handshake (replied to with K)
 *   K|<sessionJson>\n                   CM → Lua: greet + session config
 *   O|<opEnvelopeJson>\n                Lua → CM: a captured editor op
 *   A|<clientOpId>|<seq>|<status>\n     CM → Lua: ack for a previously sent O frame
 *                                       status = "ok" | "rejected:<reason>"
 *   R|<opEnvelopeJson>\n                CM → Lua: a remote op for Lua to apply
 *   N|<envBatchJson>\n                  Lua → CM: batched scene-globals diffs
 *                                       payload = { batch: [{key,value,ts}…] }
 *   M|<envObservationJson>\n            CM → Lua: a single remote env observation
 *                                       payload = { authorId, ts, key, value }
 *   F|<fieldBatchJson>\n                Lua → CM: batched per-object field writes
 *                                       payload = { batch: [{pid,fieldName,arrayIndex,value,ts}…] }
 *   G|<fieldWriteJson>\n                CM → Lua: a single remote field write
 *                                       payload = { authorId, ts, pid, fieldName, arrayIndex, value }
 *   Z|<requestJson>\n                   CM → host Lua: build a snapshot now
 *                                       payload = { snapshotId? } (optional id to correlate)
 *                                   OR: joiner Lua → CM: snapshot apply ack
 *                                       payload = { snapshotId, ok, error? }
 *   Y|<chunkJson>\n                     host Lua → CM: one snapshot chunk
 *                                       payload = { snapshotId, index, total, byteLength, payload, levelName?, createdTs }
 *   B|<chunkJson>\n                     CM → joiner Lua: one snapshot chunk to apply
 *                                       payload = { snapshotId, index, total, payload, baseSeq?, levelName? }
 *   T|<brushJson>\n                     either direction: one brush stroke frame (Phase 4)
 *                                       payload = { strokeId, brushType, kind:'begin'|'tick'|'end', payload, ts, authorId? }
 *   P|\n                                ping (either direction)
 *   Q|\n                                pong (either direction)
 *   E|<msg>\n                           soft error (informational)
 *
 * "Phase 1 only" responsibilities of this class:
 *   - bind a loopback port, write `we_port.txt`
 *   - accept exactly one Lua client; replace prior client on reconnect
 *   - parse incoming frames, emit typed events
 *   - queue outbound frames while the client is disconnected (capped)
 *
 * Phase 2+ will plug an `EditorSyncRelayService` on top of these events; this
 * class deliberately knows nothing about sessions, peers, or persistence.
 */

import { createServer, type Server, type Socket } from 'net'
import { createInterface, type Interface as ReadlineInterface } from 'readline'
import { writeFileSync, existsSync, unlinkSync } from 'fs'
import { EventEmitter } from 'events'
import { join } from 'path'

export interface LuaHello {
  /** BeamNG build string reported by the Lua side, if available. */
  beamngBuild?: string
  /** Whether the world editor is currently active in-game. */
  editorActive?: boolean
  /** Currently loaded level name, if any. */
  levelName?: string | null
  /** Anything else the Lua side wants to surface (best-effort). */
  [k: string]: unknown
}

/** A captured op as the Lua side hands it off. The CM relay re-stamps `seq`. */
export interface LuaOpEnvelope {
  /** "do" | "undo" | "redo" — the editor history kind. */
  kind: 'do' | 'undo' | 'redo'
  /** UUID generated by Lua before sending; used in the `A` ack. */
  clientOpId: string
  /** Wall-clock ms (Lua-side; advisory). */
  ts: number
  /** Action name from `editor.history:commitAction`. Always set for "do". */
  name?: string
  /**
   * Normalised, JSON-safe action data. For Phase 1 this is whatever the Lua
   * `sanitise` helper produced (no netId rewriting yet).
   */
  data?: unknown
  /** Per-action human-readable detail (matches `EditorSyncCaptureEntry.detail`). */
  detail?: string
  /** Object/road ids the action references (Phase 1: local sim ids). */
  targets?: number[]
}

export interface BridgeAck {
  clientOpId: string
  seq: number
  status: 'ok' | string
}

/** Local-Lua pose tick. Sent over the bridge as a `V` frame at ~5 Hz. */
export interface LuaPose {
  /** Wall-clock ms, Lua-side. */
  ts: number
  x: number
  y: number
  z: number
  /** Heading in radians (yaw), if known. */
  heading?: number
  /** `true` when the player is currently driving a vehicle. */
  inVehicle?: boolean
  /** Vehicle JBeam name ("etk800") if inVehicle. */
  vehicle?: string
  /** Current level name at the time of this tick. */
  levelName?: string | null
}

/**
 * Single env observation as the Lua side reports it inside an N| batch
 * payload (`{ batch: [LuaEnvObservation, …] }`). The bridge socket emits one
 * `env` event per batch entry — fan-out happens here so downstream code only
 * has to handle the per-key shape.
 */
export interface LuaEnvObservation {
  /** Registered ENV_KEYS entry, e.g. "tod", "weather", "gravity", "simSpeed". */
  key: string
  /** Opaque per-key value (number for tod/gravity/simSpeed, string for weather, …). */
  value: unknown
  /** Wall-clock ms, Lua-side. */
  ts: number
}

/**
 * Single per-object field write as reported inside an F| batch payload
 * (`{ batch: [LuaFieldObservation, …] }`). Captured either by the
 * `cmSetField` helper or the 1 Hz polling diff (TRACKED_FIELDS).
 */
export interface LuaFieldObservation {
  /** Target object's BeamNG persistentId (UUID string). */
  pid: string
  fieldName: string
  /** Default 0 — only relevant for vector/array-typed fields. */
  arrayIndex: number
  /** Opaque per-field value. */
  value: unknown
  /** Wall-clock ms, Lua-side. */
  ts: number
}

/**
 * One chunk of a snapshot as reported by the host Lua over a Y| frame.
 * The bridge socket emits one event per chunk; the relay accumulates by
 * `snapshotId` until it has `total` chunks, then forwards as session frames.
 */
export interface LuaSnapshotChunk {
  snapshotId: string
  index: number
  total: number
  byteLength: number
  payload: string
  levelName?: string | null
  createdTs: number
}

/** Joiner-side Lua reports snapshot apply success/failure via Z| from Lua. */
export interface LuaSnapshotAck {
  snapshotId: string
  ok: boolean
  error?: string
}

/**
 * One brush stroke frame as captured by host or joiner Lua via the
 * `cmBrushBegin`/`cmBrushTick`/`cmBrushEnd` helpers (Phase 4).
 */
export interface LuaBrushObservation {
  strokeId: string
  brushType: string
  kind: 'begin' | 'tick' | 'end'
  payload: unknown
  ts: number
}

interface Events {
  hello: (info: LuaHello) => void
  op: (env: LuaOpEnvelope) => void
  pose: (pose: LuaPose) => void
  env: (obs: LuaEnvObservation) => void
  field: (obs: LuaFieldObservation) => void
  /** A snapshot chunk arrived from host Lua — forward to relay for caching. */
  snapshotChunk: (chunk: LuaSnapshotChunk) => void
  /** Joiner-side: local Lua acked a snapshot apply. */
  snapshotApplied: (ack: LuaSnapshotAck) => void
  /** Phase 4: a single brush-stroke frame (begin/tick/end) emitted by Lua. */
  brush: (obs: LuaBrushObservation) => void
  ack: (ack: BridgeAck) => void
  /** Lua connected (after first frame, not just TCP accept). */
  ready: () => void
  /** Lua disconnected (game closed, extension undeployed, or socket dropped). */
  disconnect: () => void
  /** Soft error reported by Lua side. */
  luaError: (msg: string) => void
}

export class EditorSyncBridgeSocket extends EventEmitter {
  private server: Server | null = null
  private client: Socket | null = null
  private rl: ReadlineInterface | null = null
  private port = 0
  private portFile: string | null = null
  private greeted = false

  /** Buffered outbound frames while no client is connected (capped). */
  private pending: string[] = []
  private static readonly PENDING_CAP = 1024

  override on<E extends keyof Events>(event: E, listener: Events[E]): this {
    return super.on(event, listener)
  }
  override emit<E extends keyof Events>(event: E, ...args: Parameters<Events[E]>): boolean {
    return super.emit(event, ...args)
  }

  /** Open the listener and write `<beamcmDir>/we_port.txt`. Idempotent. */
  async start(beamcmDir: string): Promise<number> {
    if (this.server) return this.port
    return await new Promise<number>((resolve, reject) => {
      const server = createServer((socket) => this.attach(socket))
      server.on('error', (err) => {
        console.error('[EditorSyncBridge] server error', err)
      })
      server.listen(0, '127.0.0.1', () => {
        const addr = server.address()
        if (typeof addr !== 'object' || addr === null) {
          reject(new Error('EditorSyncBridge: failed to acquire port'))
          return
        }
        this.server = server
        this.port = addr.port
        this.portFile = join(beamcmDir, 'we_port.txt')
        try {
          writeFileSync(this.portFile, String(this.port), 'utf-8')
        } catch (e) {
          reject(e)
          return
        }
        console.log(`[EditorSyncBridge] listening on 127.0.0.1:${this.port}`)
        resolve(this.port)
      })
    })
  }

  stop(): void {
    if (this.client) {
      try { this.client.destroy() } catch { /* ignore */ }
    }
    this.client = null
    this.rl?.close()
    this.rl = null
    if (this.server) {
      try { this.server.close() } catch { /* ignore */ }
      this.server = null
    }
    if (this.portFile && existsSync(this.portFile)) {
      try { unlinkSync(this.portFile) } catch { /* ignore */ }
    }
    this.portFile = null
    this.pending = []
    this.greeted = false
  }

  isConnected(): boolean {
    return this.client !== null && !this.client.destroyed
  }

  /** Send a session-greeting K frame after Lua's H handshake. */
  greet(payload: Record<string, unknown>): void {
    this.write('K|' + JSON.stringify(payload) + '\n')
  }

  /**
   * Acknowledge a previously sent O frame. Status string is opaque; convention
   * is "ok" for accept, "rejected:<reason>" otherwise.
   */
  ack(clientOpId: string, seq: number, status: 'ok' | string = 'ok'): void {
    // Defensive: clientOpId must not contain '|' or newline (UUIDs don't).
    const safe = clientOpId.replace(/[|\n\r]/g, '')
    this.write(`A|${safe}|${seq}|${status}\n`)
  }

  /** Push a remote op down to Lua for application. */
  sendRemoteOp(env: unknown): void {
    this.write('R|' + JSON.stringify(env) + '\n')
  }

  /**
   * Push a peer's pose down to Lua so it can render an in-world ghost marker.
   * Ephemeral — no ack, no retry. Drop on the floor if the bridge is closed.
   */
  sendRemotePose(pose: unknown): void {
    this.write('S|' + JSON.stringify(pose) + '\n')
  }

  /**
   * Push a single remote env observation down to Lua for application. The
   * relay calls this once per peer per env-key change; Lua suppresses the
   * apply path's own re-capture so we don't echo.
   */
  sendRemoteEnv(env: unknown): void {
    this.write('M|' + JSON.stringify(env) + '\n')
  }

  /**
   * Push a single remote field write down to Lua for application. The relay
   * already filtered echoes by authorId; Lua sets suppressFieldCapture during
   * apply to stop the polling diff from re-emitting the value next tick.
   */
  sendRemoteField(field: unknown): void {
    this.write('G|' + JSON.stringify(field) + '\n')
  }

  /**
   * Ask the host Lua to build a snapshot. The returned snapshot arrives as
   * one or more `snapshotChunk` events. Caller passes a snapshotId so it can
   * correlate the response with its outstanding request.
   */
  requestSnapshot(req: { snapshotId: string }): void {
    this.write('Z|' + JSON.stringify(req) + '\n')
  }

  /**
   * Push a snapshot chunk down to a joiner-side Lua for reassembly + apply.
   * The joiner Lua replies via a Z| frame (emitted as `snapshotApplied`)
   * once all chunks have arrived and been applied (success or failure).
   */
  sendSnapshotChunk(chunk: unknown): void {
    this.write('B|' + JSON.stringify(chunk) + '\n')
  }

  /**
   * Push a single remote brush frame down to Lua for replay (Phase 4).
   * Same letter (T|) is used in both directions — the relay filters echoes
   * by authorId so the originator's Lua never receives its own frames.
   */
  sendRemoteBrush(brush: unknown): void {
    this.write('T|' + JSON.stringify(brush) + '\n')
  }

  /** Send a soft error message (Lua will log it). */
  sendError(msg: string): void {
    this.write('E|' + msg.replace(/[\r\n]/g, ' ') + '\n')
  }

  private write(line: string): void {
    if (this.client && !this.client.destroyed) {
      this.client.write(line)
      return
    }
    if (this.pending.length >= EditorSyncBridgeSocket.PENDING_CAP) {
      this.pending.shift()
    }
    this.pending.push(line)
  }

  private attach(socket: Socket): void {
    if (this.client) {
      console.log('[EditorSyncBridge] replacing previous client connection')
      try { this.client.destroy() } catch { /* ignore */ }
      this.rl?.close()
    }
    this.client = socket
    this.greeted = false
    socket.setNoDelay(true)
    socket.on('error', (err) => {
      console.warn('[EditorSyncBridge] socket error', err.message)
    })
    socket.on('close', () => {
      if (this.client === socket) {
        console.log('[EditorSyncBridge] client disconnected')
        this.client = null
        this.rl?.close()
        this.rl = null
        this.greeted = false
        this.emit('disconnect')
      }
    })

    this.rl = createInterface({ input: socket, crlfDelay: Infinity })
    this.rl.on('line', (raw) => this.dispatch(raw))

    console.log(`[EditorSyncBridge] client connected from ${socket.remoteAddress}:${socket.remotePort}`)

    if (this.pending.length > 0) {
      console.log(`[EditorSyncBridge] flushing ${this.pending.length} buffered frame(s)`)
      for (const line of this.pending) socket.write(line)
      this.pending = []
    }
  }

  private dispatch(line: string): void {
    if (!line) return
    const type = line.charCodeAt(0)

    // O — captured op (highest volume)
    if (type === 0x4f /* O */) {
      const json = line.substring(2)
      let env: LuaOpEnvelope
      try {
        env = JSON.parse(json) as LuaOpEnvelope
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed O frame', err)
        return
      }
      this.emit('op', env)
      return
    }

    // V — pose tick (ephemeral, high volume)
    if (type === 0x56 /* V */) {
      const json = line.substring(2)
      let pose: LuaPose
      try {
        pose = JSON.parse(json) as LuaPose
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed V frame', err)
        return
      }
      this.emit('pose', pose)
      return
    }

    // N — env-channel batch (ephemeral, low volume — 4 Hz max). Fan out the
    // batch into one `env` event per entry so the relay can do per-key LWW.
    if (type === 0x4e /* N */) {
      const json = line.substring(2)
      let payload: { batch?: unknown }
      try {
        payload = JSON.parse(json) as { batch?: unknown }
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed N frame', err)
        return
      }
      const batch = Array.isArray(payload?.batch) ? payload.batch : []
      for (const raw of batch) {
        if (!raw || typeof raw !== 'object') continue
        const obs = raw as LuaEnvObservation
        if (typeof obs.key !== 'string' || typeof obs.ts !== 'number') continue
        this.emit('env', obs)
      }
      return
    }

    // F — field-channel batch (4 Hz max). Same fan-out pattern as N.
    if (type === 0x46 /* F */) {
      const json = line.substring(2)
      let payload: { batch?: unknown }
      try {
        payload = JSON.parse(json) as { batch?: unknown }
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed F frame', err)
        return
      }
      const batch = Array.isArray(payload?.batch) ? payload.batch : []
      for (const raw of batch) {
        if (!raw || typeof raw !== 'object') continue
        const obs = raw as LuaFieldObservation
        if (typeof obs.pid !== 'string' || typeof obs.fieldName !== 'string') continue
        if (typeof obs.ts !== 'number') continue
        if (typeof obs.arrayIndex !== 'number') obs.arrayIndex = 0
        this.emit('field', obs)
      }
      return
    }

    // Y — snapshot chunk emitted by host Lua in response to a Z| request.
    if (type === 0x59 /* Y */) {
      const json = line.substring(2)
      let chunk: LuaSnapshotChunk
      try {
        chunk = JSON.parse(json) as LuaSnapshotChunk
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed Y frame', err)
        return
      }
      if (typeof chunk.snapshotId !== 'string' || typeof chunk.index !== 'number') return
      if (typeof chunk.total !== 'number' || typeof chunk.payload !== 'string') return
      this.emit('snapshotChunk', chunk)
      return
    }

    // Z (from Lua) — snapshot apply ack from a joiner-side Lua.
    if (type === 0x5a /* Z */) {
      const json = line.substring(2)
      let ack: LuaSnapshotAck
      try {
        ack = JSON.parse(json) as LuaSnapshotAck
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed Z frame', err)
        return
      }
      if (typeof ack.snapshotId !== 'string') return
      this.emit('snapshotApplied', ack)
      return
    }

    // T — Phase 4 brush stroke frame from Lua. Begin/Tick/End discriminated
    // by `kind`. The relay broadcasts to peers (filtering out the originator
    // by authorId) and applies a 30 Hz tick cap on top of Lua's own.
    if (type === 0x54 /* T */) {
      const json = line.substring(2)
      let obs: LuaBrushObservation
      try {
        obs = JSON.parse(json) as LuaBrushObservation
      } catch (err) {
        console.warn('[EditorSyncBridge] malformed T frame', err)
        return
      }
      if (typeof obs.strokeId !== 'string' || typeof obs.brushType !== 'string') return
      if (obs.kind !== 'begin' && obs.kind !== 'tick' && obs.kind !== 'end') return
      if (typeof obs.ts !== 'number') return
      this.emit('brush', obs)
      return
    }

    // H — handshake (low frequency, once per connect)
    if (type === 0x48 /* H */) {
      const json = line.substring(2)
      let info: LuaHello = {}
      if (json.length > 0) {
        try {
          info = JSON.parse(json) as LuaHello
        } catch (err) {
          console.warn('[EditorSyncBridge] malformed H frame', err)
        }
      }
      if (!this.greeted) {
        this.greeted = true
        this.emit('hello', info)
        this.emit('ready')
      }
      return
    }

    // P/Q — heartbeat. Reply Q to P; ignore Q.
    if (type === 0x50 /* P */) {
      this.write('Q|\n')
      return
    }
    if (type === 0x51 /* Q */) {
      return
    }

    // E — soft error from Lua
    if (type === 0x45 /* E */) {
      const msg = line.substring(2)
      this.emit('luaError', msg)
      return
    }

    console.warn('[EditorSyncBridge] unknown frame type', JSON.stringify(line.substring(0, 32)))
  }
}
